version: '3.8'
services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - .:/var/www:delegated
      - ./tools/docker/web/config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    restart: unless-stopped
    image: php:8.2-fpm
    volumes:
      - .:/var/www:delegated
    depends_on:
      - db
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://root:root@database:3306/ChatSymfony?serverVersion=8&charset=utf8mb4

  db:
    image: 'mysql:8'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ChatSymfony
    volumes:
      - ./var:/var/www/var
      - ./tools/docker/mysql:/var/lib/mysql

  adminer:
    image: adminer
    environment:
      APP_ENV: dev
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN : pepa-linha
    ports:
      - 8888:8080

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:8000
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    volumes:
      - mercure_data:/data
      - mercure_config:/config

volumes:
  db-data:
    driver: local
  mercure_data:
  mercure_config:
networks:
  dev:
    driver: bridge
